import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import Image from 'next/image';
import logo from '@/public/images/logo.svg';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Devriazul Portfolio || Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
            <div className="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
              <a href="/" className="flex items-center">
                <Image src="https://devriazul.com/img/devriazul.svg" alt="Flowbite Logo" className="mr-3 h-6 sm:h-9" width={150} height={150} />
                <span className="self-center text-xl font-semibold whitespace-nowrap dark:text-white"></span>
              </a>
              <div className="flex items-center lg:order-2">
                <a href="#" className="text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">
                  Log in
                </a>
                <button data-collapse-toggle="mobile-menu-2" type="button" className="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu-2" aria-expanded="false">
                  <span className="sr-only">Open main menu</span>
                  <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fillRule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd"></path>
                  </svg>
                  <svg className="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd"></path>
                  </svg>
                </button>
              </div>
              <div className="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
                <ul className="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
                  <li>
                    <Link href="/" className="block py-2 pr-4 pl-3 text-white rounded bg-primary-700 lg:bg-transparent lg:text-primary-700 lg:p-0 dark:text-white" aria-current="page">
                      Home
                    </Link>
                  </li>
                  <li>
                    <Link href="/about" className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">
                      About
                    </Link>
                  </li>
                  {/* <li>
                    <Link href="/resume" className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">
                      Resume
                    </Link>
                  </li> */}
                  <li>
                    <Link href="/projects" className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">
                      Projects
                    </Link>
                  </li>
                  <li>
                    <Link href="/blogs" className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">
                      Blogs
                    </Link>
                  </li>
                  <li>
                    <Link href="/contact" className="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">
                      Contact
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        {children}
        <footer className="bg-white text-gray-900 dark:bg-gray-800 dark:text-white">
          <div className="max-w-screen-xl mx-auto py-8 px-4 md:px-6">
            <div className="flex flex-col items-center text-center">
              <a href="/" className="flex items-center mb-4">
                <Image
                  src="https://devriazul.com/img/devriazul.svg"
                  alt="DevRiazul Logo"
                  className="mr-3 h-8 sm:h-10"
                  width={150}
                  height={150}
                />
                {/* <span className="text-2xl font-semibold">DevRiazul</span> */}
              </a>
              <p className="mb-6 text-gray-500 dark:text-gray-400">
              A showcase of my work and projects, designed to highlight my skills in web development and offer insights into my creative process.
              </p>
              <ul className="flex flex-wrap justify-center gap-4 mb-6">
                <li>
                  <Link href="/" className="text-gray-700 dark:text-gray-400 hover:text-primary-700 dark:hover:text-white">
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="/about" className="text-gray-700 dark:text-gray-400 hover:text-primary-700 dark:hover:text-white">
                    About
                  </Link>
                </li>
                <li>
                  <Link href="/projects" className="text-gray-700 dark:text-gray-400 hover:text-primary-700 dark:hover:text-white">
                    Projects
                  </Link>
                </li>
                <li>
                  <Link href="/blogs" className="text-gray-700 dark:text-gray-400 hover:text-primary-700 dark:hover:text-white">
                    Blogs
                  </Link>
                </li>
                <li>
                  <Link href="/contact" className="text-gray-700 dark:text-gray-400 hover:text-primary-700 dark:hover:text-white">
                    Contact
                  </Link>
                </li>
              </ul>
              <span className="text-sm text-gray-500 dark:text-gray-400">
                © 2024 <a href="#" className="hover:underline">DevRiazul™</a>. All Rights Reserved.
              </span>
            </div>
          </div>
        </footer>

      </body>
    </html>
  );
}
